const products = [
    {
        id: 1,
        title: "Monitor 24",
        price: 20000,
        description: "Monitor de 24 pulgadas FullHD",
        category: "Monitor",
        image: "../media/img/tv24.jpg",
        stock: 20,
        offer: "",
    },
    {
        id: 2,
        title: "Monitor 32",
        price: 25000,
        description: "Monitor de 32 pulgadas 4K",
        category: "Monitor",
        image: "../media/img/tv32.jpg",
        stock: 17,
        offer: "",
    },
    {
        id: 3,
        title: "Teclado mecanico 60%",
        price: 7000,
        description: "Teclado mecanico con switches outemu red, compacto de 60%",
        category: "Teclado",
        image: "../media/img/teclado60.jpg",
        stock: 8,
        offer: 25,
    },
    {
        id: 4,
        title: "Teclado mecanico full",
        price: 10700,
        description: "Teclado mecanico completo con switches cherry brown",
        category: "Teclado",
        image: "../media/img/tecladofull.jpg",
        stock: 10,
        offer: 15,
    },
    {
        id: 5,
        title: "Mouse inalambrico",
        price: 5000,
        description: "Mouse inalambrico con conexion bluetooth y 2.4ghz",
        category: "Mouse",
        image: "../media/img/mousein.jpeg",
        stock: 15,
        offer: "",
    },
    {
        id: 6,
        title: "Mouse 2000 dpi",
        price: 4500,
        description: "Mouse cableado con luz RGB",
        category: "Mouse",
        image: "../media/img/mousecable.jpg",
        stock: 10,
        offer: "",
    },
    {
        id: 7,
        title: "Mouse pad",
        price: 3300,
        description: "Mouse pad compacto",
        category: "MousePad",
        image: "../media/img/mousepad.jpg",
        stock: 50,
        offer: 50,
    },
    {
        id: 8,
        title: "Mouse pad XXL",
        price: 4200,
        description: "Mouse pad tama;o XXL",
        category: "MousePad",
        image: "../media/img/mousepadxxl.jpg",
        stock: 43,
        offer: 70,
    }
];

export default products;